import Head from "next/head";
import { Inter } from "next/font/google";
import Landing from "../components/Landing/index";
import LandingContainer from "@/components/LandingContainer";
import Landing_JobStyle from "@/components/Landing-job-style";
import Footer from "@/components/Footer";
import Landing_product from "@/components/Landing-product";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col ">
        <Landing />
        <LandingContainer />
        <Landing_JobStyle />
        <Landing_product />
        <Footer />
      </div>
    </>
  );
}
